### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by micksulley** [sandyol55/Ropey-Cam#1]
Just discovered this project after months of looking and trying to figure out from the manual.  This looks brilliant!!
When I first ran it it failed with "list index out of range", I checked through and discovered that if I changed line 44 to read
"cam_mode_select =0" it runs fine.  Testing shows that 0, 1, 2 work fine but anything above seems to give the error.
The comment says # Pick the most suitable mode for your sensor
but I don't know what it does and so don't know what is most suitable.  Could you tell me please?
Many thanks
Mick

**Comment by sandyol55** [comment]
Hi Mick,
Guess you must be using a camera with only three 'advertised' modes . Possibly a V3 camera?
The 'best' mode is likely to be the one with the highest advertised frame rate, and/or the maximum FOV, depending on how you wish to use it.
In the case of the V2 IMX219 camera -which is what I'm currently running with - mode 5 gives the best combination of framerate and FOV for my use.
See section 4.2.2.3. Raw streams and the Sensor Configuration in the picamera2 manual 
https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf
 for some background to choosing a sensor mode.
I really should get round to tidying the code up and documenting a bit better if other people are going to make some use of it, though it really was an exercise for myself to try and learn !! 
Edit :  fix link to manual
Edit 3 : I'd suggest mode 0 is the 'best' mode for a V3 camera as it gives the the highest framerate with a reasonable FOV.

**Comment by micksulley** [comment]
Thanks for the info.  Yes using a v3 on a Pi5.  I had tried the code in that section of the manual but it errors, so reverted to trial an error.
I have set the sensor mode to 0 and it is running fine.
